### ISSUE TITLE
Accuracy of Data In Visitor Profile

### ISSUE THREAD

**Issue by AaronThomas22** [merchantprotocol/capital-audience-support#18]
I just installed the pixel on my client's website. The client is a LOCAL home services contractor (roofing, siding, gutters, solar, windows). But, all the traffic that is listed in the identified visitor profiles are ALL out of state and not even near Pennsylvania. I could understand a few, but when the majority of the traffic to my client's site should be PA, MD, and DE, and absolutely no visitor profile is from any of those three or surrounding states has me worried.

Is this a bug? Or is the data not accurate? Is it pulling from someone else's pixel?

<img width="893" alt="Screenshot 2023-01-10 at 6 21 56 AM" src="https://user-images.githubusercontent.com/105283193/211541436-d9dd7bc5-8bbf-450a-876f-27f35fc5b6a7.png">

Attaching a screenshot and happy to do a Loom to to get this resolved.

**Comment by jonathonbyrdziak** [comment]
https://github.com/merchantprotocol/capital-audience-support/discussions/19
