### ISSUE TITLE
Unable To Access Site

### ISSUE THREAD

**Issue by AaronThomas22** [merchantprotocol/capital-audience-support#20]
I get an HTTP Error code 503 when trying to access (https://targeting.capitalaudience.com/).

<img width="1440" alt="Screenshot 2023-01-12 at 9 16 14 AM" src="https://user-images.githubusercontent.com/105283193/212090157-b7e5f670-e546-420c-94ab-8eae3e9a92e3.png">

**Comment by jonathonbyrdziak** [comment]
Thanks @AaronThomas22 we dug deep into this instability and have resolved it.
