### ISSUE TITLE
500 Server Error

### ISSUE THREAD

**Issue by AaronThomas22** [merchantprotocol/capital-audience-support#21]
I receive a 500 Server Error when clicking on the Visitors Profile and Visitor Log.

Here's a Loom Video: https://www.loom.com/share/dfd13e2ce9054eb3886b22c5aac94c47

**Comment by alancarvalho** [comment]
Hi @AaronThomas22 

Thanks for reached out to us.
This issue fixed. Please confirm it from your side.

Regards,

CC: @1231707
