### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by Mwdpond** [merchantprotocol/capital-audience-support#31]
When you look at the targeting KWs of a enabled campaign for a custom audience, the KWs just appear as [object object]. Not a big deal as long as it still works, but just figured I'd let you know. Thanks! 

![Screenshot 2023-06-01 at 9 52 23 AM](https://github.com/merchantprotocol/capital-audience-support/assets/135088206/5ec97a05-cd38-42a6-9ba4-23e5f4f4c82c)

**Comment by alancarvalho** [comment]
Hi @Mwdpond 

We are looking into this now. Could you please confirm your Audience Name or show your browser console on this page?

**Comment by alancarvalho** [comment]
Hi @Mwdpond 

Not necessary. We found the issue.

**Comment by alancarvalho** [comment]
Hi @Mwdpond 

Issue fixed.
